name: Call a reusable workflow 

on:
  workflow_dispatch:
    inputs:
      client_repository:
        description: 'repository'
      branch:
        description: 'branch'
      user_id:
        description: 'user_id'

jobs:
  Deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Call Reusable Workflow
        uses: American-Chip/workflow-remote/.github/workflows/graviton-scan-reusable.yaml@develop
        with:
          CLIENT_REPOSITORY: ${{ github.event.inputs.client_repository }}
          BRANCH : ${{ github.event.inputs.branch }}
          USER_id : ${{ github.event.inputs.user_id }}
          ac_github_token: ${{ secrets.Token_WF }}
